# Generated by Django 3.2.9 on 2021-12-03 03:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20191122_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='address',
            field=models.CharField(default='HealthPlus, GT-22, Mumbai', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 33, 43, 875543)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2021, 12, 3, 8, 33, 43, 875543)),
        ),
        migrations.CreateModel(
            name='profile_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstname', models.CharField(max_length=250)),
                ('u_nm', models.CharField(max_length=150)),
                ('urmail', models.EmailField(max_length=254)),
                ('unicode', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
