# Generated by Django 3.2.9 on 2021-12-03 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211203_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='end_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='host',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 3, 8, 42, 14, 96223)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2021, 12, 3, 8, 42, 14, 96223)),
        ),
    ]
