# Generated by Django 3.2.9 on 2021-12-05 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211205_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='T_10to11',
            new_name='t10to11',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='T_11to12',
            new_name='t11to12',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='T_13to14',
            new_name='t13to14',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='T_14to15',
            new_name='t14to15',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='T_15to16',
            new_name='t15to16',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='T_16to17',
            new_name='t16to17',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='T_9to10',
            new_name='t9to10',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 5, 12, 14, 23, 495893)),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='time_in',
            field=models.TimeField(default=datetime.datetime(2021, 12, 5, 12, 14, 23, 495893)),
        ),
    ]
