# Generated by Django 3.2.9 on 2021-12-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211205_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time_slott',
            field=models.CharField(default='9to10', max_length=50),
        ),
    ]
