# Generated by Django 3.2.9 on 2021-12-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_meeting_time_slott'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time_slott',
            field=models.CharField(default='t9to10', max_length=50),
        ),
    ]
