# Generated by Django 3.2.9 on 2021-12-07 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211206_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 7)),
        ),
    ]
