# Generated by Django 3.2.9 on 2021-12-10 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_meeting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 10)),
        ),
    ]
