# Generated by Django 3.2.9 on 2021-12-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_meeting_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_details',
        ),
    ]
