# Generated by Django 3.2.9 on 2021-12-10 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0023_delete_profile_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fstname', models.CharField(max_length=250)),
                ('u_nm', models.CharField(max_length=150)),
                ('urmail', models.EmailField(max_length=254)),
                ('unicode', models.CharField(max_length=100, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
